theme: jekyll-theme-minimal

title: Khmer Typing
email: support@passerellesnumeriques.org
description: >- 
  Khmer typing will help you to develop your typing abilities in Khmer
  It contains a visual keyboard to help you to master the NiDA dispostion
  and some games to improve your typing speed.
baseurl: "/khmer-typing-website"
url: "https://passerelles-numeriques.github.io"
twitter_username: passerellesnume
github_username: "passerelles-numeriques"
logo: "images/icon-512x512.png"